[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
solc = '0.8.20'
optimizer = true
optimizer_runs = 200
ffi = true

[rpc_endpoints]
celo = '${CELO_RPC_URL}'
base = '${BASE_RPC_URL}'
jello = '${JELLO_RPC_URL}'

[fuzz]
max_test_rejects = 65536
runs = 256
